#!/usr/bin/env python3
"""
Code Agent — A Claude Code clone using fully free AI models.
Supports: Gemini, Groq, OpenRouter, Together AI, Ollama, Cohere, Mistral, HuggingFace

Usage:
    python main.py                          # Interactive mode
    python main.py "your task here"         # One-shot mode
    python main.py --provider groq          # Use Groq provider
    python main.py --model llama3.2         # Use specific model
    python main.py --workspace /path/to/dir # Set working directory
    python main.py --safe                   # Enable safe mode
"""

import sys
import os
import argparse
import json
from pathlib import Path


def check_dependencies():
    missing = []
    try:
        import rich
    except ImportError:
        missing.append("rich")
    try:
        import dotenv
    except ImportError:
        pass

    if missing:
        print(f"Missing required dependencies: {', '.join(missing)}")
        print(f"Run: pip install {' '.join(missing)}")
        sys.exit(1)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Code Agent — A Claude Code clone using free AI models",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python main.py                              # Start interactive session
  python main.py "add docstrings to main.py" # Run one task
  python main.py --provider groq              # Use Groq (fastest)
  python main.py --provider ollama            # Use local Ollama
  python main.py --provider openrouter --model google/gemini-2.0-flash-exp:free

Free API keys:
  Gemini:      https://aistudio.google.com/app/apikey
  Groq:        https://console.groq.com
  OpenRouter:  https://openrouter.ai/keys
  Together:    https://api.together.xyz
  Cohere:      https://dashboard.cohere.com/api-keys
  Mistral:     https://console.mistral.ai/api-keys
  HuggingFace: https://huggingface.co/settings/tokens
  Ollama:      https://ollama.ai (runs locally, no key needed)
        """,
    )
    parser.add_argument("task", nargs="?", help="Task to run in one-shot mode")
    parser.add_argument("--provider", "-p", help="AI provider (gemini/groq/openrouter/together/ollama/cohere/mistral/huggingface)")
    parser.add_argument("--model", "-m", help="Model name")
    parser.add_argument("--workspace", "-w", default=".", help="Working directory (default: current)")
    parser.add_argument("--safe", action="store_true", help="Enable safe mode (confirm before file writes/commands)")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose tool output")
    parser.add_argument("--no-stream", action="store_true", help="Disable streaming")
    parser.add_argument("--max-iterations", type=int, default=50, help="Max tool-calling iterations per turn")
    parser.add_argument("--providers", action="store_true", help="List all providers and their models")
    parser.add_argument("--setup", action="store_true", help="Run interactive setup wizard")
    parser.add_argument("--version", action="version", version="Code Agent 1.0.0")
    return parser.parse_args()


def show_providers():
    from providers.factory import get_all_provider_info
    from agent.display import console, COLORS
    from rich.table import Table
    from rich import box

    info = get_all_provider_info()
    table = Table(
        title="Available AI Providers (All Free)",
        box=box.ROUNDED,
        border_style=COLORS["primary"],
        header_style=f"bold {COLORS['secondary']}",
        show_lines=True,
    )
    table.add_column("Provider", style=f"bold {COLORS['tool']}", no_wrap=True)
    table.add_column("Key Env Var", style=COLORS["warning"])
    table.add_column("Best Free Model", style=COLORS["text"])
    table.add_column("Tools", style=COLORS["success"])
    table.add_column("Notes", style=COLORS["dim"])

    for key, p in info.items():
        table.add_row(
            key,
            p["key_env"] or "None needed",
            p["models"][0] if p["models"] else "-",
            "✓" if p["tools"] else "✗",
            p["notes"][:60],
        )
    console.print(table)


def setup_wizard():
    from agent.display import console, COLORS, print_info, print_success, print_warning
    from rich.prompt import Prompt, Confirm
    from providers.factory import get_all_provider_info

    console.print(f"\n[bold {COLORS['primary']}]Code Agent Setup Wizard[/]\n")
    info = get_all_provider_info()

    env_path = Path(".env")
    existing = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()

    lines = ["# Code Agent Configuration", "# Generated by setup wizard", ""]
    
    print_info("Choose your primary AI provider:")
    for i, (k, v) in enumerate(info.items()):
        note = f"  — {v['notes'][:50]}"
        console.print(f"  [{i+1}] {k:15s} {note}")

    console.print()
    choice_str = Prompt.ask("Enter number (1-8)", default="1")
    try:
        choice_idx = int(choice_str) - 1
        chosen = list(info.keys())[max(0, min(choice_idx, len(info)-1))]
    except Exception:
        chosen = "gemini"

    lines.append(f"AI_PROVIDER={chosen}")
    lines.append(f"AI_MODEL={info[chosen]['models'][0]}")
    lines.append("")

    console.print(f"\n[{COLORS['success']}]Setting up {chosen}...[/]")
    if info[chosen]["key_env"]:
        console.print(f"Get your free API key: [{COLORS['info']}]{info[chosen]['get_key']}[/]")
        key_val = existing.get(info[chosen]["key_env"], "")
        if key_val:
            use_existing = Confirm.ask(f"Found existing {info[chosen]['key_env']}. Keep it?", default=True)
            if not use_existing:
                key_val = Prompt.ask(f"Enter {info[chosen]['key_env']}", password=True)
        else:
            key_val = Prompt.ask(f"Enter {info[chosen]['key_env']} (or press Enter to skip)", default="", password=True)
        if key_val:
            lines.append(f"{info[chosen]['key_env']}={key_val}")

    lines.append("\n# Optional: Set keys for other providers to switch between them")
    for k, v in info.items():
        if k != chosen and v["key_env"]:
            lines.append(f"# {v['key_env']}=your_key_here")

    lines.extend([
        "\n# Agent settings",
        "MAX_ITERATIONS=50",
        "BASH_TIMEOUT=30",
        "# SAFE_MODE=true   # Uncomment to require confirmation before file writes",
        "# VERBOSE=true     # Uncomment for detailed tool output",
    ])

    env_path.write_text("\n".join(lines))
    print_success(f"Configuration saved to .env")
    print_info(f"Run 'python main.py' to start the agent.")


def register_all_tools(workspace_getter):
    from tools.file_tools import register_file_tools
    from tools.bash_tool import register_bash_tools
    from tools.search_tools import register_search_tools
    from tools.web_tools import register_web_tools
    from tools.git_tools import register_git_tools
    from tools.utility_tools import register_utility_tools

    register_file_tools(workspace_getter)
    register_bash_tools(workspace_getter)
    register_search_tools(workspace_getter)
    register_web_tools(workspace_getter)
    register_git_tools(workspace_getter)
    register_utility_tools(workspace_getter)


def run_interactive(agent, config):
    from agent.display import (
        print_banner, print_help, prompt_user, clear_screen,
        print_success, print_error, print_info, print_warning,
        print_separator, print_status_table, print_diff, console, COLORS
    )
    from agent.context import ConversationContext
    from providers.factory import get_all_provider_info
    from pathlib import Path
    import readline
    readline.set_history_length(1000)

    print_banner(config.provider, config.model)

    while True:
        try:
            user_input = prompt_user()
        except (KeyboardInterrupt, EOFError):
            print_warning("\nUse /exit to quit.")
            continue

        user_input = user_input.strip()
        if not user_input:
            continue

        if user_input.startswith("/"):
            parts = user_input.split(None, 2)
            cmd = parts[0].lower()
            args = parts[1] if len(parts) > 1 else ""
            rest = parts[2] if len(parts) > 2 else ""

            if cmd in ("/exit", "/quit", "/q"):
                print_info("Goodbye!")
                break

            elif cmd == "/help":
                print_help()

            elif cmd == "/clear":
                clear_screen()
                agent.context.reset()
                print_banner(config.provider, config.model)

            elif cmd == "/reset":
                agent.context.reset()
                print_success("Conversation history cleared.")

            elif cmd == "/provider":
                if not args:
                    info = get_all_provider_info()
                    for k, v in info.items():
                        mark = "★" if k == config.provider else " "
                        console.print(f"  {mark} [{COLORS['tool']}]{k}[/] — {v['models'][0]}")
                else:
                    model_override = rest if rest else ""
                    if agent.switch_provider(args, model_override):
                        agent.context.reset()

            elif cmd == "/model":
                if not args:
                    if hasattr(agent.provider, 'list_models'):
                        models = agent.provider.list_models()
                        console.print(f"Available models for {config.provider}:")
                        for m in models:
                            mark = "★" if m == config.model else " "
                            console.print(f"  {mark} {m}")
                    else:
                        print_info(f"Current model: {config.model}")
                else:
                    config.model = args
                    agent._load_provider()
                    print_success(f"Switched to model: {args}")

            elif cmd == "/models":
                if hasattr(agent.provider, "list_models"):
                    models = agent.provider.list_models()
                    for m in models:
                        console.print(f"  • {m}")

            elif cmd == "/providers":
                from main import show_providers
                show_providers()

            elif cmd == "/status":
                print_status_table(agent.status)

            elif cmd == "/history":
                console.print(agent.context.format_history())

            elif cmd == "/compact":
                result = agent.compact_history()
                print_info(result)

            elif cmd == "/cost":
                stats = agent.context.get_stats()
                print_status_table(stats)

            elif cmd == "/verbose":
                agent.verbose = not agent.verbose
                config.verbose = agent.verbose
                state = "ON" if agent.verbose else "OFF"
                print_info(f"Verbose mode: {state}")

            elif cmd == "/safe":
                agent.safe_mode = not agent.safe_mode
                config.safe_mode = agent.safe_mode
                state = "ON" if agent.safe_mode else "OFF"
                print_info(f"Safe mode: {state}")

            elif cmd == "/cd":
                if not args:
                    print_info(f"Current directory: {agent.context.workspace}")
                else:
                    new_dir = Path(agent.context.workspace) / args
                    try:
                        new_dir = new_dir.resolve()
                        if new_dir.is_dir():
                            agent.context.workspace = str(new_dir)
                            os.chdir(new_dir)
                            print_success(f"Changed directory to: {new_dir}")
                        else:
                            print_error(f"Directory not found: {args}")
                    except Exception as e:
                        print_error(str(e))

            elif cmd == "/pwd":
                print_info(f"Working directory: {agent.context.workspace}")

            elif cmd == "/ls":
                from tools.file_tools import list_directory
                result = list_directory(args or ".", workspace=agent.context.workspace)
                console.print(result)

            elif cmd == "/run":
                if args:
                    from tools.bash_tool import run_command
                    result = run_command(f"{args} {rest}".strip(), workspace=agent.context.workspace)
                    console.print(result)

            elif cmd == "/save":
                if args:
                    path = Path(args)
                    agent.context.save(path)
                    print_success(f"Conversation saved to {args}")
                else:
                    print_error("Usage: /save <filename>")

            elif cmd == "/load":
                if args:
                    path = Path(args)
                    if path.exists():
                        agent.context.load(path)
                        print_success(f"Loaded conversation from {args}")
                    else:
                        print_error(f"File not found: {args}")

            elif cmd == "/undo":
                op = agent.context.pop_undo()
                if op:
                    print_info(f"Undo: {op}")
                else:
                    print_info("Nothing to undo.")

            elif cmd == "/init":
                from tools.utility_tools import init_project
                ptype = args or "python"
                name = rest or Path(agent.context.workspace).name
                result = init_project(ptype, name, agent.context.workspace)
                console.print(result)

            elif cmd == "/memory":
                stats = agent.context.get_stats()
                print_status_table(stats)
                console.print(f"\n[{COLORS['dim']}]Tool categories: {list(registry.list_by_category().keys())}[/]")

            else:
                print_warning(f"Unknown command: {cmd}. Type /help for help.")
        else:
            try:
                agent.run(user_input)
            except KeyboardInterrupt:
                print_warning("\nTask interrupted. Use /exit to quit.")
            except Exception as e:
                print_error(f"Agent error: {e}")
                if config.verbose:
                    import traceback
                    traceback.print_exc()


def main():
    check_dependencies()
    args = parse_args()

    if args.providers:
        show_providers()
        return

    if args.setup:
        setup_wizard()
        return

    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass

    from agent.config import Config
    config = Config()

    if args.provider:
        config.provider = args.provider.lower()
        config.model = config.get_default_model(config.provider)
    if args.model:
        config.model = args.model
    if args.safe:
        config.safe_mode = True
    if args.verbose:
        config.verbose = True
    if args.no_stream:
        config.stream = False
    if args.max_iterations:
        config.max_iterations = args.max_iterations

    workspace = str(Path(args.workspace).resolve())
    if not Path(workspace).is_dir():
        print(f"Error: Workspace directory not found: {workspace}")
        sys.exit(1)

    os.chdir(workspace)

    from agent.context import ConversationContext
    context = ConversationContext(workspace=workspace)

    register_all_tools(lambda: context.workspace)

    from agent.core import Agent
    from tools.registry import registry

    agent = Agent(config, context)

    if args.task:
        from agent.display import print_user_message
        print_user_message(args.task)
        result = agent.run(args.task)
        if result:
            print(result)
        return

    run_interactive(agent, config)


if __name__ == "__main__":
    main()







